version: '3'

networks:
  backend:
    driver: bridge
  gateway:
    external: true

services:
  ubc-api:
    image: ubc:test
    container_name: ubc
    environment:
      - TZ=Asia/Shanghai
    privileged: true
    volumes:
      - ./etc/:/app/etc/
    ports:
      - "8888:8888"
    stdin_open: true
    tty: true
    networks:
      - gateway
    restart: always


  ubc-web:
    container_name: ubc-web
    image: ubc-web:test
    environment:
      - TZ=Asia/Shanghai
    privileged: true
    stdin_open: true
    tty: true
    networks:
      - gateway
    restart: always