// Code generated by goctl. DO NOT EDIT.
package types

type SignInRequest struct {
	Name     string `json:"name,optional"`     // 邮箱
	Password string `json:"password,optional"` // 密码
}

type SignInResponse struct {
	Token        string `json:"token"`        // 访问令牌
	AccessExpire int64  `json:"accessExpire"` // 访问令牌过期时间
	RefreshAfter int64  `json:"refreshAfter"` // 刷新令牌时间
	Role         string `json:"role"`         // 角色
}

type Shipment struct {
	BillOfLanding   string `json:"billOfLanding,optional"`   // 提单
	CustomerCode    string `json:"customerCode,optional"`    // 客户代码
	ShipFrom        string `json:"shipFrom,optional"`        // 发货地
	ShipMethod      string `json:"shipMethod,optional"`      // 运输方式
	CountryOfOrigin string `json:"countryOfOrigin,optional"` // 原产国
	Manufacture     string `json:"manufacture,optional"`     // 制造商
	VesselFlight    string `json:"vesselFlight,optional"`    // 船/航班
	ETDDt           int64  `json:"etdDt,optional"`           // 预计离港日期
	UBCPI           string `json:"ubcPi,optional"`           // UBC PI
	MarksAndNumbers string `json:"marksAndNumbers,optional"` // 标记和号码
}

type Packing struct {
	PO     string  `json:"po,optional"`     // 采购订单号
	Style  string  `json:"style,optional"`  // 款式
	Color  string  `json:"color,optional"`  // 颜色
	ProjID int     `json:"projId,optional"` // projection id
	UBCPI  string  `json:"ubcPi,optional"`  // UBC PI
	Price  float64 `json:"price,optional"`  // 价格
	Carton int     `json:"carton,optional"` // 纸箱数量
	QtyPC  int     `json:"qtyPC,optional"`  // 数量（件）
	GWKG   int     `json:"gwKg,optional"`   // 毛重（千克）
	NWKG   int     `json:"nwKg,optional"`   // 净重（千克）
	Meas   int     `json:"meas,optional"`   // 尺寸
}

type Invoice struct {
	InvoiceCode    string  `json:"invoiceCode,optional"`    // 发票代码
	AdditionalCost float64 `json:"additionalCost,optional"` // 附加费用
	DepositAmt     float64 `json:"depositAmt,optional"`     // 定金金额
	InvoiceDt      int64   `json:"invoiceDt,optional"`      // 发票日期
	InvoiceDue     int64   `json:"invoiceDue,optional"`     // 发票到期日
}

type ShipmentAndInvoice struct {
	ShipmentId      int     `json:"shipmentId,optional"`
	InvoiceId       int     `json:"invoiceId,optional"`
	BillOfLanding   string  `json:"billOfLanding,optional"`   // 提单
	CustomerCode    string  `json:"customerCode,optional"`    // 客户代码
	ShipFrom        string  `json:"shipFrom,optional"`        // 发货地
	ShipMethod      string  `json:"shipMethod,optional"`      // 运输方式
	CountryOfOrigin string  `json:"countryOfOrigin,optional"` // 原产国
	Manufacture     string  `json:"manufacture,optional"`     // 制造商
	VesselFlight    string  `json:"vesselFlight,optional"`    // 船/航班
	ETDDt           int64   `json:"etdDt,optional"`           // 预计离港日期
	UBCPI           string  `json:"ubcPi,optional"`           // UBC PI
	MarksAndNumbers string  `json:"marksAndNumbers,optional"` // 标记和号码
	InvoiceCode     string  `json:"invoiceCode,optional"`     // 发票代码
	AdditionalCost  float64 `json:"additionalCost,optional"`  // 附加费用
	DepositAmt      float64 `json:"depositAmt,optional"`      // 定金金额
	InvoiceDt       int64   `json:"invoiceDt,optional"`       // 发票日期
	InvoiceDue      int64   `json:"invoiceDue,optional"`      // 发票到期日
}

type ShipmentAndInvoiceRes struct {
	ShipmentId int `json:"shipmentId"`
	InvoiceId  int `json:"invoiceId"`
}

type UpdateShippingInfo struct {
	BillOfLading    string `json:"billOfLading,optional"`    // 提单号
	CustomerCode    string `json:"customerCode,optional"`    // 客户代码
	MasterPO        string `json:"masterPO,optional"`        // 主采购订单号
	RMBInvoice      string `json:"rmbInvoice,optional"`      // 人民币发票
	ShipDate        string `json:"shipDate,optional"`        // 装运日期
	MarksAndNumbers string `json:"marksAndNumbers,optional"` // 标记和编号
	ShipFrom        string `json:"shipFrom,optional"`        // 发货地
	ShipMethod      string `json:"shipMethod,optional"`      // 运输方式
	CountryOfOrigin string `json:"countryOfOrigin,optional"` // 原产国
	Term            string `json:"term,optional"`            // 术语
	UBCPI           string `json:"ubcPI,optional"`           // UBC PI
	MasterBINum     string `json:"masterBINum,optional"`     // 主BI号
	Exporter        string `json:"exporter,optional"`        // 出口商
	ShipName        string `json:"shipName,optional"`        // 船名
	ShipDt          int64  `json:"shipDt,optional"`          // 装运日期
	ETDDt           int64  `json:"etdDt,optional"`           // 预计出发日期
	InvoiceTtl      string `json:"invoiceTtl,optional"`      // 发票标题
	Notes           string `json:"notes,optional"`           // 备注
}

type SaveShipment struct {
	ShipmentInfo Shipment `json:" shipmentAndInvoice,optional"`
}

type SaveShipmentRes struct {
	ShinmentId string `json:"shinmentId"`
}

type UploadRes struct {
	Res interface{} `json:"res"`
}

type QueryShipment struct {
	PageNo       int    `json:"pageNo,default=0"`
	PageSize     int    `json:"pageSize,default=10"`
	SearchParams string `json:"searchParams,optional"`
	Order        string `json:"order,optional"`
}

type ListRes struct {
	Res      interface{} `json:"res"`
	Total    int         `json:"total"`
	PageNo   int         `json:"pageNo"`
	PageSize int         `json:"pageSize"`
}

type PackingListReq struct {
	ShipmentId int `json:"shapmentId"`
	Total      int `json:"total"`
	PageNo     int `json:"pageNo"`
	PageSize   int `json:"pageSize"`
}

type UploadFile struct {
	UsedFor string `form:"usedFor"`
}

type UploadFileRes struct {
	Po        string `json:"customerPo"`
	Color     string `json:"color"`
	Style     string `json:"styleCode"`
	SalePrice string `json:"salePrice"`
	CartonCnt string `json:"cartonCnt"`
	MeasVol   string `json:"measVol"`
}

type SearchAllCustomerAndPrijection struct {
	Customers   interface{} `json:"customers"`
	Projections interface{} `json:"projections"`
}
